### ISSUE TITLE
Very poor performance on ARMv8

### ISSUE THREAD

**Issue by KyleGospo** [gekigek99/minecraft-server-hibernation#109]
After compiling the latest-available go code, running the MSH application uses 25% (100% of 1 core) of my 2Ghz Raspberry Pi 4B's CPU while idle.

The older Python version is using far less than 1% under the same circumstance. Please let me know what info I can provide to help debug this.

Software otherwise works without issue.

**Comment by gekigek99** [comment]
what version are you using?

I want to point out that since version 2.2.1 the minecraft server is launched as a child process of msh.  
This implies that when the server is running, a great increase in resource usage by msh has to be expected (99% of which are used by the mincraft server child process and not by msh proxy/manager itself).  

What is the resource usage when msh is running with mincraft server being offline vs it being online?

**Comment by KyleGospo** [comment]
@gekigek99 Glad you mentioned the dev branch, that seems much better!

Previously, I compiled 2.4.0 and that 100% usage was immediately after launch, nobody on the server. On dev, that's completely gone.

**Comment by gekigek99** [comment]
Glad to hear it solved the problem!

Guess the mistery will remain unsolved tho...

**Comment by gekigek99** [comment]
This is the most recent commit as of today (for reference): 72a25e4e2caafd0bde4cd5c559d767e2a0a2bcfa

@KyleGospo if you like this rep please consider giving a star!
