### ISSUE TITLE
Doesn't work on Paper servers

### ISSUE THREAD

**Issue by SorrowEater** [gekigek99/minecraft-server-hibernation#83]
I realize that this was never the intention, but hibernation thinks that it's still warming up when it's done...

**Comment by gekigek99** [comment]
ok that should be a simple fix... just need to ask few questions...

- what msh version are you using?
- can you share the log from msh? (I need specifically the minecraft server output, but send it fully just to be sure)

**Comment by SorrowEater** [comment]
I'm using version 2.3.0, and the output is the same as normal, I'll pastebin it: https://paste.ubuntu.com/p/wb5nyfjbTx/

**Comment by SorrowEater** [comment]
The Hibernation part is a plugin I'm using temporarily until I can get this to work

**Comment by gekigek99** [comment]
ok would you mind using the lastest version? (as already said in the discussion, I think you are experiencing that bug related to modded minecraft servers)

I'm attaching the compiled binary here
[minecraft-server-hibernation-v2.3.3.zip](https://github.com/gekigek99/minecraft-server-hibernation/files/6193000/minecraft-server-hibernation-v2.3.3.zip)

**beware that this might not work since I see some differences in the loading log of your minecraft server**
(_if that is the case please set debug to true and send the full log, I'll fix the problem and update the code as soon as possible_)

---

> The Hibernation part is a plugin I'm using temporarily until I can get this to work

I don't really understand what you are referring to...

**Comment by SorrowEater** [comment]
>I don't really understand what you are referring to...
"[15:01:20 INFO]: [Hibernate] Loading Hibernate v2.0.0"
That's all that I was referring to, nothing major...
I'll test the new version and come back to you with the results!

**Comment by SorrowEater** [comment]
Ok, so it still doesn't work with the new version. The server is running, but hibernation doesn't realize that and doesn't redirect traffic to the jar. Unless the script's use case is simply to probe it in order to turn the server on, and then join from a different ip, the problem is that the script simply doesn't realize that the server has started...

**Comment by SorrowEater** [comment]
The log is pretty normal: https://paste.ubuntu.com/p/fnQwbB3DB6/

**Comment by gekigek99** [comment]
ok I'll explain to you what is happening:

msh to recognize that the server is online looks for a log line that contains: `[Server thread/INFO]` and `Done`
the problem is that paper servers communicates that the server is online using: `INFO` and `Done`

take a look [here](https://github.com/gekigek99/minecraft-server-hibernation/blob/c2c84a9a244e1d37c710303c9befcb950e3a57fc/lib/servctrl/cmd.go#L165)

this is why msh thinks that the server never reaches the "online" status

this should fix the problem
[minecraft-server-hibernation-v2.3.3_paper-bugfix.zip](https://github.com/gekigek99/minecraft-server-hibernation/files/6198387/minecraft-server-hibernation-v2.3.3_paper-bugfix.zip)

after you confirm that it works I'll commit the bugfix on github

**Comment by gekigek99** [comment]
bugfix: 4cb52cfaa6ee23386e70df438fa2a5b0b606ae38
