### ISSUE TITLE
Progress bar when waking server from hibernation always shows 0%

### ISSUE THREAD

**Issue by astrooom** [gekigek99/minecraft-server-hibernation#93]
When waking the server up from hibernation, the message always shows "Server start command issued. Please wait... 0%" and you have to go back to the server list and connect to the server.

Is this something that can be fixed or is it impossible for the time being?

**Comment by gekigek99** [comment]
If you wait 20/30 seconds and then try to reconnect are you able to join the server?

Unless there is a problem in starting the server this has to be expected... if you are the first player you need to join, then return to server list and, after few seconds, try to join again.  
I don't think this can be fixed since the minecraft client cannot join a server after it has received a warning message from the server (but I hope to be wrong)

(This might actually be fixable with an enormous update of which this is the issue: #51, by unfreezing the server in half a second the warning message can be avoided and the first player almost does not notice that the server needs time to "wake up")

The message `Server start command issued. Please wait... 0%` is a static message which is not updated live... to update the message and visualize the server loading status you need to try to join again.  
(be aware that for servers that take 10 seconds to load, 90% of wait time the percent counter shows 0% and reaches 100% abruptly only in the last second: this has nothing to do with msh but it's how the minecraft server shows the loading percentage)

**Comment by astrooom** [comment]
Yes, the server boots up fine and can be joined without any issues. I was refering to the live update thing as you explain here. It would be an amazing feature if it could be implemented, but I understand it is very difficult and is limitation of Minecraft itself(?).

**Comment by gekigek99** [comment]
Yea i think that it is just how the minecraft client works... but I don't know everything and maybe its possible...

Do you have some examples of servers that have a live update of an error message? (not just the normal "loading", "logging in", "encrypting" ecc... since they are not messages sent from the server but it's the client that manages them (I'm 99% sure))
